# Generated by Django 3.2.19 on 2023-05-24 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='tribuna',
            field=models.CharField(choices=[('peluza_nord', 'Peluză Nord'), ('peluza_sud', 'Peluză Sud'), ('tribuna_1', 'Tribuna 1'), ('tribuna_2', 'Tribuna 2')], default=0, max_length=20),
        ),
    ]
