# Generated by Django 4.2.1 on 2023-05-22 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_site', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='event',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
