# Generated by Django 4.2.1 on 2023-06-11 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="end_date",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="start_date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
