# Generated by Django 3.2.19 on 2023-05-10 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eveniment',
            old_name='event',
            new_name='user',
        ),
    ]
